-- Ledger imutavel: cada transferencia concluida gera um registro. A consulta de
-- movimentacoes le daqui (nao deriva do saldo). Nunca sofre UPDATE/DELETE.
CREATE TABLE movements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id  BIGINT         NOT NULL REFERENCES accounts (id),
    to_account_id    BIGINT         NOT NULL REFERENCES accounts (id),
    amount           NUMERIC(19, 2) NOT NULL,
    status           VARCHAR(20)    NOT NULL,
    idempotency_key  VARCHAR(120),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT chk_movements_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_movements_from_account ON movements (from_account_id, created_at DESC);
CREATE INDEX idx_movements_to_account   ON movements (to_account_id, created_at DESC);
